"""
Tests for the label generation module.
"""

import unittest
import numpy as np
import pandas as pd

from src.labeling.label_generator import LabelGenerator, LabelGeneratorError


class TestLabelGenerator(unittest.TestCase):
    """Test suite for the LabelGenerator class."""

    def setUp(self):
        """Set up standard test data."""
        # Simple dataframe with increasing and decreasing prices to trigger all labels
        # Prices: 100 -> 105 (5% return, BUY) -> 100 (-4.7% return, SELL) -> 101 (1% return, HOLD) -> 101
        self.df = pd.DataFrame({
            "Date": pd.date_range(start="2023-01-01", periods=5),
            "Close": [100.0, 105.0, 100.0, 101.0, 101.0],
            "Other_Feature": [1, 2, 3, 4, 5]
        })

    def test_buy_label_generation(self):
        """Test that a BUY label is generated correctly."""
        # Horizon = 1, Buy threshold = 3%
        generator = LabelGenerator(prediction_horizon=1, buy_threshold=0.03, sell_threshold=-0.03)
        df_out = generator.generate_labels(self.df.copy())
        
        # At index 0, Close=100. Future(1)=105. Return = 0.05 >= 0.03 -> BUY
        self.assertEqual(df_out.loc[0, "Label"], "BUY")

    def test_sell_label_generation(self):
        """Test that a SELL label is generated correctly."""
        generator = LabelGenerator(prediction_horizon=1, buy_threshold=0.03, sell_threshold=-0.03)
        df_out = generator.generate_labels(self.df.copy())
        
        # At index 1, Close=105. Future(1)=100. Return = -0.0476 <= -0.03 -> SELL
        self.assertEqual(df_out.loc[1, "Label"], "SELL")

    def test_hold_label_generation(self):
        """Test that a HOLD label is generated correctly."""
        generator = LabelGenerator(prediction_horizon=1, buy_threshold=0.03, sell_threshold=-0.03)
        df_out = generator.generate_labels(self.df.copy())
        
        # At index 2, Close=100. Future(1)=101. Return = 0.01 (between -0.03 and 0.03) -> HOLD
        self.assertEqual(df_out.loc[2, "Label"], "HOLD")

    def test_nan_removal(self):
        """Test that NaNs generated by shifting are removed."""
        generator = LabelGenerator(prediction_horizon=2)
        original_len = len(self.df)
        df_out = generator.generate_labels(self.df.copy())
        
        # If horizon is 2, the last 2 rows will have NaN for Future_Close and should be dropped
        self.assertEqual(len(df_out), original_len - 2)
        self.assertFalse(df_out.isnull().values.any())

    def test_missing_close_column(self):
        """Test validation error for missing Close column."""
        df_invalid = self.df.drop(columns=["Close"])
        generator = LabelGenerator()
        with self.assertRaises(LabelGeneratorError):
            generator.generate_labels(df_invalid)

    def test_empty_dataframe(self):
        """Test behavior with an empty DataFrame."""
        df_empty = pd.DataFrame(columns=["Date", "Close"])
        generator = LabelGenerator()
        df_out = generator.generate_labels(df_empty)
        self.assertEqual(len(df_out), 0)

    def test_invalid_thresholds(self):
        """Test that invalid thresholds raise a LabelGeneratorError."""
        with self.assertRaises(LabelGeneratorError):
            LabelGenerator(buy_threshold=-0.05, sell_threshold=0.05)
            
        with self.assertRaises(LabelGeneratorError):
            LabelGenerator(buy_threshold=0.03, sell_threshold=0.03)

    def test_invalid_forecast_horizon(self):
        """Test that invalid forecast horizon raises a LabelGeneratorError."""
        with self.assertRaises(LabelGeneratorError):
            LabelGenerator(prediction_horizon=0)
            
        with self.assertRaises(LabelGeneratorError):
            LabelGenerator(prediction_horizon=-5)

    def test_columns_added(self):
        """Test that Future_Close, Future_Return, and Label columns are added."""
        generator = LabelGenerator(prediction_horizon=1)
        df_out = generator.generate_labels(self.df.copy())
        
        self.assertIn("Future_Close", df_out.columns)
        self.assertIn("Future_Return", df_out.columns)
        self.assertIn("Label", df_out.columns)


if __name__ == "__main__":
    unittest.main()
